### ISSUE TITLE
Cannot play this song, please try another

### ISSUE THREAD

**Issue by vanderheyde** [muer-org/muer#5]
Hi,

The majority of the songs I try to play receive an error "Cannot play this song, please try another".
This includes both official music videos and random ones.

The logs show no error:
```
got video
GET /videoData/pnJM_jC7j_4?_data=routes%2FvideoData.%24videoId 200 - - 3114.234 ms
```

After the red bar with the error has become visible on the page, I periodically see the following error in the logs:
```
ErrorResponse {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/web/index.html"',
  error: Error: No route matches URL "/web/index.html"
      at getInternalRouterError (/root/muer/node_modules/@remix-run/router/router.ts:4087:5)
      at Object.query (/root/muer/node_modules/@remix-run/router/router.ts:2592:19)
      at handleDocumentRequestRR (/root/muer/node_modules/@remix-run/server-runtime/dist/server.js:163:35)
      at requestHandler (/root/muer/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
      at /root/muer/node_modules/@remix-run/express/dist/server.js:39:28
}
HEAD /web/index.html 404 - - 4.224 ms
```

I'm selfhosting this installation:
debian 11
npm v9.8.0
node v20.5.0

Has something gone wrong with my installation?

Thanks!

**Comment by tri2820** [comment]
It seems this could be due to (1) Invidious server is down or (2) Youtube disallows embedded video from playing.
Will add more informative error pop-up, but for now try to refresh the page (Muer will wire you to a different Invidious server) and see if the error persists.

**Comment by vanderheyde** [comment]
Refreshing rarely has any effect, unfortunately.

**Comment by mariushosting** [comment]
To solve the issue you need to run it via https not local http.

**Comment by vanderheyde** [comment]
@mariushosting my hero! This did indeed seem to fix it; songs I was having issues with previously seem to play now.
